### ISSUE TITLE
Proxy Host header?

### ISSUE THREAD

**Issue by sime** [jcrugzz/proxy-server#1]
Would it be possible to proxy the 'Host' header.

e.g. dev.example.com resolves to 127.0.0.1

``` shell
$ proxy-server --target dev.example.com:8080 --port 8090
```

When I hit http://localhost:8090, the Host sent to 127.0.0.1 is 'dev.example.com'

**Comment by jcrugzz** [comment]
@sime this is now possible in `1.2.0` by specifying the `change-origin` option.

``` sh
$ proxy-server --target dev.example.com:8080 --port 8090 --change-origin
```

Will do what you expect. It just passes in true to [`http-proxy`](https://github.com/nodejitsu/node-http-proxy) to do the work for us :).

**Comment by sime** [comment]
:+1:
